# Generated by Django 5.1.6 on 2025-02-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
    ]
